added bucket

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -5,6 +5,15 @@ on:
     branches:
       - main
 
+  workflow_dispatch:
+    inputs:
+      action:
+        description: 'Terraform action (apply or destroy)'
+        required: true
+        default: 'apply'
+        type: string
+
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -66,8 +75,15 @@ jobs:
       run: |
         terraform plan -var-file="terraform.tfvars"
 
-    - name: Terraform Apply
+    - name: Terraform Apply or Destroy
       env:
           GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
       run: |
-        terraform destroy
+        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+          terraform apply -var-file="terraform.tfvars" -auto-approve;
+        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+          terraform destroy -var-file="terraform.tfvars" -auto-approve;
+        else
+          echo "Invalid action specified: ${{ github.event.inputs.action }}";
+          exit 1;
+        fi
