improve apply and destroy process

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -8,11 +8,10 @@ on:
   workflow_dispatch:
     inputs:
       action:
-        description: 'Terraform action (apply or destroy)'
+        description: 'This helps choose Terraform action (apply or destroy)'
         required: true
         default: 'apply'
         type: string
-
 
 jobs:
   build:
@@ -67,25 +66,22 @@ jobs:
         echo 'image           = "europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-engr-test/go-time-api:latest"' >> terraform.tfvars
         echo 'project         = "${{ secrets.GCP_PROJECT_ID }}"' >> terraform.tfvars
         echo 'region          = "${{ secrets.REGION }}"' >> terraform.tfvars
-        echo 'k8s_context     = "${{ secrets.K8S_CONTEXT }}"' >> terraform.tfvars
 
-        
-    - name: Terraform Destroy
+    - name: Terraform Plan
       env:
           GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
       run: |
-        terraform force-unlock -force 1725379517522311
-        terraform destroy -auto-approve
+        terraform plan -var-file="terraform.tfvars"
 
-    # - name: Terraform Plan
-    #   env:
-    #       GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
-    #   run: |
-    #     terraform force-unlock -force 1725376469627058
-    #     terraform plan -var-file="terraform.tfvars"
-
-    # - name: Terraform Apply or Destroy
-    #   env:
-    #       GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
-    #   run: |
-    #     terraform apply -var-file="terraform.tfvars" -auto-approve
+    - name: Terraform Apply or Destroy
+      env:
+          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
+      run: |
+        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+          terraform apply -var-file="terraform.tfvars" -auto-approve;
+        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+          terraform destroy -var-file="terraform.tfvars" -auto-approve;
+        else
+          echo "Invalid action specified: ${{ github.event.inputs.action }}";
+          exit 1;
+        fi
