Defined tf files in README

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -82,3 +82,29 @@ jobs:
           GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
       run: |
         terraform destroy -auto-approve
+
+    # New Step: Wait for API to be Ready
+    - name: Wait for API readiness
+      run: |
+        echo "Waiting for API to be ready..."
+        sleep 10  
+
+    - name: Verify API is accessible
+      run: |
+        API_ENDPOINT=$(kubectl get ingress go-time-apps -n go-time-apps -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+        if [ -z "$API_ENDPOINT" ]; then
+          echo "Ingress address not found."
+          exit 1
+        fi
+        echo "Ingress address: $API_ENDPOINT"
+
+        # Test the API endpoint
+        echo "Hitting the API at http://${API_ENDPOINT}/time"
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${API_ENDPOINT}/time)
+        echo "Response Code: $RESPONSE"
+        if [ "$RESPONSE" -ne 200 ]; then
+          echo "API is not accessible or returned unexpected response code."
+          exit 1
+        fi
+        echo "API is accessible and returned a 200 OK response."
+
